### ISSUE TITLE
Potential incompatibility with multiple values

### ISSUE THREAD

**Issue by mislav** [darobin/formic#10]
Ruby on Rails [generates this when you render a checkbox](https://gist.github.com/mislav/a2466f69b964b2e163f9) for a field:

``` html
  <input name="book[title]" type="hidden" value="0">
  <input id="book_title" name="book[title]" type="checkbox" value="1">
```

It does this so there would always be a default value, even if the checkbox wasn't checked. Both values are sent and on the server, the latter value overrides the former. With JSON form submit, two values would be sent and on the server, they would become an array.

/cc @tobie

**Comment by rodneyrehm** [comment]
The same holds true for PHP. In Ruby, using the [CGI module](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/cgi/rdoc/CGI.html#class-CGI-label-Parameters), you can access `book[title]` both ways - either getting the last defined value (in your case `"1"`), or all values (in your case `["0", "1"]`).

The "simplification" to a single value is done by the receiving environment, as the data sent by the browser is `book[title]=0&book[title]=1` (a list of keys that can, but must not necessarily be parsed to array). JSON can't handle duplicate keys, so the only way to provide all the data and keep letting the receiving enviroment decide how to deal with the incoming data would be to send all the data as array.

As far as I know this behavior was never specified anywhere. That's why every environment rolled their own approach.

**Comment by mislav** [comment]
Agreed that this is a choice of the receiving environment that can go both ways and not necessarily a shortcoming of the spec. I just wanted to point out what could potentially break if browsers start shipping with JSON encoding support tomorrow.

With a JSON form serialization, how do you envision the receiver distinguishing between these two intended use-cases (last value "wins" vs. array of values)?

**Comment by rodneyrehm** [comment]
> With a JSON form serialization, how do you envision the receiver distinguishing between these two intended use-cases (last value "wins" vs. array of values)?

The same way it is handled by the receiving environment right now? If it expects a single value, it will pick the last item of the array. If it expects multiple values, it picks the whole array. This behavior is application logic (possibly rooted in a framework).

**Comment by mislav** [comment]
Fair enough. It's just that with url-encoded and a specific backend such as Rails, it was possible for client-side to "pick" which mode it wants by either omitting or appending square brackets (`[]`). This distinction is not possible per current JSON forms draft as these are treated identically:

``` html
<input name="title">
<input name="title">

and

<input name="title[]">
<input name="title[]">
```

Feel free to close this as a non-issue, though. I agree that backends could be taught to perform this distinction themselves based on the expected type and not based on the fact whether the keys had square brackets or not.

**Comment by darobin** [comment]
I would content that 1) what Rails does is a dirty hack that shouldn't be needed (if a value is a boolean, casting missing to false ought to be okay), 2) given a JSON array it's still possible to implement that behaviour.

**Comment by tobie** [comment]
Rails does a dirty hack? Who would have thought?
