### ISSUE TITLE
Be more restrictive about keys

### ISSUE THREAD

**Issue by hybrist** [darobin/formic#27]
This contradicts the common HTML approach of "try to parse even the most obvious junk" but I'd like the following example to just fail:

``` html
<form enctype='application/json'>
  <input name='error[good]' value='BOOM!'>
  <input name='error[bad' value='BOOM BOOM!'>
</form>
```

I don't think it really helps anyone to allow a key like `error[bad`. Especially since this allows even more subtle error conditions like `obj[this is meant ] to all be one key]`. Maybe optional quoting could help here?

**Comment by macek** [comment]
There's been a lot of discussion about this, but I have to say that I'm of the opinion that no data should be lost with any given submission.

What's the worst case scenario here anyway? If `error[bad` shows up the on the server, wouldn't that be an obvious thing to go fix in your form?

Or, if the form isn't in your control, it's no different than any non-whitelisted parameter. I don't really see the problem here.

By dropping the parameter, you've enforced an arbitrary opinion that adds no actual benefit. Considering you have to sanitize the inputs anyway, removing the "bad" parameter doesn't save you any work.

**Comment by hybrist** [comment]
I was not talking about removing bad parameters - I was talking about failing to serialize the form and not submitting it. This issue contains two parts:
1. By not providing any escape mechanism, certain keys are not expressible in certain contexts. E.g. `this is meant ] to be one key` can never be used as a "sub-key" but it can be used as a top-level key. Which seems like a gap/consistency issue.
2. By mixing meta- and identifier characters and not having a strong separation, there's no well-defined failure path. There's a somewhat complex algorithm doing the conversation. By having a rule like "when in doubt, just sent the whole expression as a key" an important debugging tool is removed: runtime errors. I belief being overly graceful here and always submitting the form - no matter what, is worse than having well-defined rules for valid input field names and straight out refusing to submit when those rules are broken, including a nice, helpful error message in the developer console. Again: I'm not talking about submitting partial data. I'm talking about not submitting any data and failing.

**Comment by macek** [comment]
@jkrems I just disagree.

A regular html form is not going to blow up if you give it 

``` html
<input name="this is meant ] to be one key" value="hello">
```

Likewise, I think the JSON form submission should not blow up either.

The serializer does the best job it can to serialize the form inputs guaranteeing that bracket pairs `[]` will nest data deeper in the resulting json structure. All other data is submitted as-is.

Why force your opinions on the end user? If the input name is "bad", a simple test should expose the bug immediately. Other than that, I'd prefer to be allowed to name inputs however I want.

**Comment by darobin** [comment]
@jkrems The choice isn't between failing or not failing, it is between failing on the client or on the server. And at that point, it's a simple choice: you should _never_ fail on the client.

We're developers, we tend to have a skewed view of the browser as a development tool. It's not! For every developer there are hundreds of users. Clicking that submit button with nothing happening, or even an error message, is the absolute worst possible user experience (yes, failure on the server could happen — but in that case you're screwed no matter what, it's still better to take the odds that something at least partially useful will happen, like storing the bad key in a JSON store so that you can fix your data when you find the bug).

If you want to have strict feedback during development — and that's a worthy requirement — that's what developer tools are for. Browsers could warn about suspicious keys in the console. Validators too. I'd be happy to entertain a pull request suggesting that (non-normatively).

Also see http://www.w3.org/TR/html-design-principles/#priority-of-constituencies

**Comment by darobin** [comment]
Closing for now — reopen if you have strong disagreements.
